export const GET_DEFAULT_MOVIES = 'GET_DEFAULT_MOVIES';
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const CLEAN_MOVIE_BY_ID = 'CLEAN_MOVIE_BY_ID';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const CLEAN_MOVIES = 'CLEAN_MOVIES';
export const GET_MOVIE_BY_GENRE = 'GET_MOVIE_BY_GENRE';
export const CLEAN_MOVIE_BY_GENRE = 'CLEAN_MOVIE_BY_GENRE';
